// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DataLayer.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DataLayer.Entities
{
    public partial interface ISMContextProcedures
    {
        Task<int> GetInvoiceSumsBySpaceAndYearAsync(Guid? spaceId, int? year, OutputParameter<decimal?> paidSum, OutputParameter<decimal?> unpaidSum, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
