// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataLayer.Entities;

[Keyless]
public partial class VBookingStatistic
{
    [Column("space_id")]
    public Guid? SpaceId { get; set; }

    [Column("year")]
    public int? Year { get; set; }

    [Column("month")]
    public int Month { get; set; }

    [Column("booked_days")]
    public int BookedDays { get; set; }
}